### ISSUE TITLE
Jersey Devil (PAL)

### ISSUE THREAD

**Issue by AD010** [flathub/org.duckstation.DuckStation#2] opened 2021-05-20 18:41 UTC
Jersey Devil (Europe) freezes on frog boss, please fix it
![SLES-00598_2021-05-20_21-41-20](https://user-images.githubusercontent.com/46242741/119031762-1f945a00-b9b4-11eb-82f8-f11de3eed8b8.png)

**Comment by j8r** [comment] 2021-05-22 12:47
Duplicate of https://github.com/stenzek/duckstation/issues/2145 and https://github.com/stenzek/duckstation/issues/2150.
This is just a packaging of DuckStation, no development on the emulator itself is actually done here.

Not an issue related related to the Flatpak package, closing.

**Closed by j8r** 2021-05-22 12:47 UTC
